### ISSUE TITLE
Temporary CodeKit addition inserted (or duplicated) several times 

### ISSUE THREAD

**Issue by fietstouring** [bdkjones/CodeKit#543] opened 2019-05-05 14:33 UTC
**Quick, short summary:**
I am working on the CSS files of a remote site using the external server address in CodeKit. Problem is that the CodeKit JS for browser refreshing is inserted 3 times in the page. As a result – when saving a CSS file it is injected several times (per save). Repeating this process results in the browser building up all the styles repeatedly until the page needs to be reloaded manually because it´s freezing.

I know that somehow the remote site produces this error. There are numerous AJAX calls going on. I would like to know at which point the CodeKit addition is inserted into the page. on page load? document ready?

**Comment by bdkjones** [comment] 2019-05-05 14:47
This problem generally happens on pages that attempt to respond to DOM element insertion/deletion actions with Javascript.

CodeKit dynamically recreates <link> tags for each stylesheet, waits until the new tags are fully loaded, then removes the old <link> tags. It does so whenever a refresh of stylesheets is called for—not at document ready or on page load. If you have Javascript that interferes with that process, you’ll see that as the behavior you’ve described.

**Comment by fietstouring** [comment] 2019-05-05 14:55
which each refresh/save all the <link> tags are duplicated, that means the old ones aren´t removed. That means something is interfering when the CodeKit JS tries to do that? Do you have any idea what could be the reason that the CodeKit JS shows up 2 additional times in the body in an element with a duplicate Id (that exists twice on the page)? 
Thanks!

**Comment by bdkjones** [comment] 2019-05-05 15:44
Is the page malformed? CodeKit’s JS block is added when the page is served. If the page is malformed at that point (for example, if you serve invalid html and rely on client-side Javascript to “fix” the page by adding things), that could explain this. CodeKit looks for a closing body tag </body> and, if found, puts the script there. Otherwise, it looks for a closing head tag and puts it there.

**Comment by bdkjones** [comment] 2019-05-05 16:50
If CodeKit’s script tag appears more than once on the page, that’s likely the cause of this issue—the refresh handler is running twice, once for each instance of CodeKit’s script tag. What is the actual source of the page that’s being served by your external server? That should be a complete html document.

**Comment by fietstouring** [comment] 2019-05-05 18:22
no it is not malformed, there is a `</body>` tag. the JS block shows up in the header. it is weird that the same nonce="" attribute also shows up in one of the `<script>` tags in the header. Also weird is that when I remove all Javascript from the head, the CodeKit JS is included correctly, only once. when I re-add jQuery as the only script, again 3 times....

**Comment by fietstouring** [comment] 2019-05-05 18:32
ok, I see that HTML-validator has problems with the page. 
`<noscript><img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=848005392214576&amp;ev=PageView&amp;noscript=1" /></noscript>`

after that it says stray end tag `<noscript> ` and after that 

> Start tag body seen but an element of the same type was already open.

**Comment by fietstouring** [comment] 2019-05-05 18:35
so although the HTML is valid, maybe the `<noscript>` tag in the `<head>` (where it shouldn´t be) causes the error...?

**Comment by bdkjones** [comment] 2019-05-05 18:51
I’d need a copy of the project to run over here to see what’s going on.

**Comment by fietstouring** [comment] 2019-05-05 19:17
I can send you the link to the site via email, other than that I have only access to a directory on the server where I can store my own CSS and JS files.

**Comment by fietstouring** [comment] 2019-05-06 09:00
I saved the response HTML to my local server and found out that there is a very simple AJAX call on the page that duplicates the CodeKit JS.

**Comment by fietstouring** [comment] 2019-05-06 09:39
quick solution is to change the AJAX call and filter out the script before writing it to the page.

**Comment by bdkjones** [comment] 2019-05-07 02:06
Ah, glad you got it sorted. Stuff like this is universally always caused by fancy JS work.

**Closed by bdkjones** 2019-05-07 02:06 UTC
