### ISSUE TITLE
"Unable to optimize this file"

### ISSUE THREAD

**Issue by clicknathan** [bdkjones/CodeKit#328] opened 2017-02-27 15:18 UTC
**Quick, short summary:**

"Unable to optimize this file" on the majority of images for the last several weeks, maybe months.

CodeKit 3.0.6

Nearly every image I try and optimize, I get the error above. This has been happening for awhile. I quit using CodeKit because of it (it's really all I use it for), but today wanted to extra-optimize my images and got the error again, so I figured I'd report it.

This happens on images that:

1. I download from the web, such as iStock Photo or Flickr.
2. Screenshots taken from my Mac.
3. Any image exported for web from Photoshop.

**Expected results:**

The image should be optimized, and I shouldn't get the error message.

**Actual results:**

The error result above.

**Exact steps to reproduce:**

Try optimizing an image in CodeKit.

**A link to download a simplified project or file that shows the issue:**

This ZIP file contains the codekit.config file, screenshots of the errors and various images that won't compress (and some that will).
https://clicknathan.com/wp-content/uploads/2017/02/codekit-errors.zip

**Your configuration (any details about your system that you think might be relevant)**

OS X El Capitan
10.11.6
Macbook Pro Retina, Mid 2012
2.6 GHz Intel Core i7
16 GB 1600 MHz DDR3

Thank you!

**Comment by bdkjones** [comment] 2017-02-28 00:31
Yea, I'm currently looking into this. I believe what I'm going to do is rip out `libjpeg` and replace it with https://github.com/libjpeg-turbo/libjpeg-turbo. I'm also going to enable lossy compression because I'm super tired of people telling me that "App XYZ makes images 1,905% smaller than CodeKit does. Why do you suck at programming?" when they don't realize they're giving up quality for those savings. This is my current focus for the next update to the app.

**Comment by clicknathan** [comment] 2017-02-28 14:49
Hah, well I don't hold that "suck at programming" opinion and love CodeKit. I should probably dig into the other features, too, my current workflow just really loves ridiculously minimized images and so I use PS + CodeKit + Smush It to try and squeeze every last drop out of these images. Google still seems to think they need to be smaller, but at least the effort is there. Looking forward to the update!

**Comment by bdkjones** [comment] 2017-03-04 08:36
Ok. I've dived into this and it turns out that by, "Cannot optimize this image," what I really mean is, "This image is already optimized so JPEGOptim skipped it."

That's not intentional and the side effect is that if you're optimizing the file to a different output path (e.g. into a build folder), CodeKit won't copy the existing (already optimal) file for you. 

The issue is fixed in the next release, which I plan to put out this weekend. Along with that, I've also added a lossy compression option for JPEGs and reworked the log statements for image optimization so that they say more than just "optimized successfully". All around, good image stuff coming in the next update.

**Closed by bdkjones** 2017-03-04 08:36 UTC
