### ISSUE TITLE
Drag 'n drop crashes app

### ISSUE THREAD

**Issue by polycode-nz** [bdkjones/CodeKit#697] opened 2022-08-17 00:47 UTC
**Quick, short summary:**
Dragging a file to the linked files prepend/append pane crashes the app.

**Expected results:**
File to be linked without a crash

**Actual results:**
No linked file, crash

**Exact steps to reproduce:**
Click a file.
Click linked files tab.
Drag a file to the "Prepend To This File" area.

**Your configuration (any details about your system that you think might be relevant)**
App version: 3.18.1 (34408)
BigSur 11.6.7

Partial report:

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x000037bec41a0520
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [392]

VM Regions Near 0x37bec41a0520:
    CoreAnimation               125dbb000-127005000    [ 18.3M] rw-/rwx SM=PRV  
--> 
    MALLOC_NANO              600000000000-600008000000 [128.0M] rw-/rwx SM=PRV  

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libobjc.A.dylib               	0x00007fff206df6b3 objc_retain + 35
1   com.incident57.CodeKit3       	0x000000010ab9de1f closure #1 in JavascriptFileInspectorController.tableView(_:acceptDrop:row:dropOperation:) + 1023
2   com.incident57.CodeKit3       	0x000000010aba2aa1 partial apply for closure #1 in JavascriptFileInspectorController.tableView(_:acceptDrop:row:dropOperation:) + 33
3   com.incident57.CodeKit3       	0x000000010abad2b1 thunk for @escaping @callee_guaranteed (@guaranteed NSDraggingItem, @unowned Int, @unowned UnsafeMutablePointer<ObjCBool>) -> () + 65
4   com.apple.AppKit              	0x00007fff236e2f59 __119-[_NSDragManager _enumerateDraggingItemsForDrag:pasteboard:withOptions:view:classes:searchOptions:isSource:usingBlock:]_block_invoke + 796
5   com.apple.CoreFoundation      	0x00007fff2092e027 __NSARRAY_IS_CALLING_OUT_TO_A_BLOCK__ + 7
6   com.apple.CoreFoundation      	0x00007fff2092dea5 -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 224
7   com.apple.AppKit              	0x00007fff236e2c18 -[_NSDragManager _enumerateDraggingItemsForDrag:pasteboard:withOptions:view:classes:searchOptions:isSource:usingBlock:] + 343
8   com.apple.AppKit              	0x00007fff236e188a -[NSDragDestination enumerateDraggingItemsWithOptions:forView:classes:searchOptions:usingBlock:] + 144
9   com.incident57.CodeKit3       	0x000000010aba1a39 specialized JavascriptFileInspectorController.tableView(_:acceptDrop:row:dropOperation:) + 873
10  com.incident57.CodeKit3       	0x000000010ab9fab7 @objc JavascriptFileInspectorController.tableView(_:acceptDrop:row:dropOperation:) + 71
11  com.apple.AppKit              	0x00007fff238ff529 -[NSTableView performDragOperation:] + 210
12  com.apple.AppKit              	0x00007fff2348bb64 NSCoreDragReceiveMessageProc + 476
13  com.apple.HIServices          	0x00007fff25bddbbb CallReceiveMessageCollectionWithMessage + 103
14  com.apple.HIServices          	0x00007fff25bd7e6b DoMultipartDropMessage + 105
15  com.apple.HIServices          	0x00007fff25bd7c61 DoDropMessage + 42
16  com.apple.HIServices          	0x00007fff25bd67ee DragInApplication + 741

**Comment by saschabregenhorn** [comment] 2022-08-19 11:19
Can confirm that.
App version: 3.18.1 (34408)
Montery 12.4

**Comment by bdkjones** [comment] 2022-08-22 05:01
I'm looking into it. At first blush, it looks like the new Swift 5.5 compiler has a bug. That's not impossible, but it's extremely rare. The code behind this part of the app has worked perfectly for a decade+ and versions of CodeKit built with Xcode 13 don't have this issue; only builds with Xcode 14 and the new Swift 5.5 compiler are exhibiting the crash. It's a bad access, meaning ARC is letting go of memory too soon.

**Comment by bdkjones** [comment] 2022-08-22 05:07
Hmm. This isn't the same as the crash in the Applescript command handlers. I'm not able to reproduce this crash. Can you send me a project that's showing the issue?

**Comment by bdkjones** [comment] 2022-08-22 07:06
@saschabregenhorn I haven't been able to reproduce this using the demo project that @polycode-nz provided. He's still on Big Sur as well, which is an additional variable. Do you have a project that reproduces the issue you can send to me?

**Comment by bdkjones** [comment] 2022-08-22 08:59
Ok, so this is fixed in 3.18.2, which is now out.

The crashes were caused by a change/bug in the Swift 5.5 compiler in Xcode 14 beta 5. Apparently, indirect pointers passed across the Objective-C to Swift boundary are now suspect.

**Closed as completed by bdkjones** 2022-08-22 08:59 UTC

**Comment by saschabregenhorn** [comment] 2022-08-22 09:03
> Ok, so this is fixed in 3.18.2, which is now out.
> 
> The crashes were caused by a change/bug in the Swift 5.5 compiler in Xcode 14 beta 5. Apparently, indirect pointers passed across the Objective-C to Swift boundary are now suspect.

Works, great! Thanks!

**Comment by polycode-nz** [comment] 2022-08-22 09:34
Perfect, fixed for me. Thanks Bryan 🍻
