### ISSUE TITLE
CodeKit "forgets" which project is open between restarts

### ISSUE THREAD

**Issue by greg-raven** [bdkjones/CodeKit#535] opened 2019-03-09 21:54 UTC
**Quick, short summary:**

If I log out of the account on my Mac, then log back in, CodeKit will forget which project I had open, so I have to reselect it.

**Expected results:**

CodeKit should remember which project is open from launch to launch.

**Actual results:**

CodeKit opens with "no open project."

**Exact steps to reproduce:**

Have CodeKit open with an active project, log out of the account you're in, closing all documents, log back in, launch CodeKit.

**A link to download a simplified project or file that shows the issue:**

I'll have to supply this later.

**Your configuration (any details about your system that you think might be relevant)**

Should be up-to-date with macOS and BBEdit.

**Comment by greg-raven** [comment] 2019-03-10 13:01
![Screen Shot 2019-03-09 at 4 39 35 PM](https://user-images.githubusercontent.com/451809/54085294-e5ba6a00-42f9-11e9-87c0-9cf15ec70047.jpg)

**Comment by bdkjones** [comment] 2019-03-10 16:36
Interesting. CodeKit saves the selected project when the app quits, but not before. It also selects the last-active project when the app launches, but no other time. I’m not sure if macOS “suspends” the app when you log out, but I’d suspect something like that is the cause.

**Comment by bdkjones** [comment] 2019-07-12 08:31
Ok, this SHOULD be addressed in the next update. I'm currently fighting Apple's notarization server to get that approved for Catalina, but I'm working on shipping it as soon as possible.

**Closed by bdkjones** 2019-07-12 08:31 UTC
