### ISSUE TITLE
Rename project through click-menu

### ISSUE THREAD

**Issue by zedley** [bdkjones/CodeKit#243] opened 2016-11-02 15:45 UTC
**Quick, short summary:** Trying to rename a project using the context menu brought up by right-clicking does nothing. I can, however, just click the name once and, after a very brief wait, rename the project no sweat.

**Expected results:** Open project pane, right-click a project and then select Rename "project-name." The name would then convert to an editable text box.

**Actual results:** Nothing.

**Exact steps to reproduce:** Right-click a project. Select Rename "project-name." Wait. It happens whether the project is enabled or disabled, currently selected (as in, the project details show behind the pane) or not.

**Comment by bdkjones** [comment] 2016-11-02 17:36
I'm not able to reproduce this over here. When I right-click a project and choose "rename", the project's text field is highlighted and goes into editing mode. This occurs in both the popover and sidebar.

**Comment by zedley** [comment] 2016-11-02 19:00
[ck_rename.zip](Video evidence)

Dunno what it could be, but I definitely can't get it to rename with the menu command.

**Comment by bdkjones** [comment] 2016-11-02 19:00
Can you try rebooting your Mac?

**Comment by zedley** [comment] 2016-11-02 19:06
Sorry, the Best Buy Deluxe Support did nothing.

**Comment by bdkjones** [comment] 2016-11-02 19:21
Ha. Well...I honestly don't know what could cause that. Do you have any accessibility features enabled?

**Comment by zedley** [comment] 2016-11-02 19:40
The only things I have checked in Accessibility are "Spring-loading delay" under Mouse & Trackpad  and "smooth images" under Zoom. Tried turning both off, but no dice.

**Comment by zedley** [comment] 2016-11-02 19:43
Aha! The culprit is Keyboard, "Full Keyboard Access." The menu rename option works with "Text Boxes and Lists Only," and does not work with "All Controls," reliably and repeatedly.

**Comment by bdkjones** [comment] 2016-11-02 19:47
Can you give me exact steps to reproduce?

**Comment by zedley** [comment] 2016-11-03 00:36
System Preferences > Keyboard. Shortcuts tab. Under "Full Keyboard Access: In windows and dialogs, press Tab to move keyboard focus between:", select "All Controls." Then try to right-click a project title and hit rename. Doesn't work. Back in System Preferences, select "Text boxes and lists only." Try to right-click a project title and hit rename. Works.

**Comment by bdkjones** [comment] 2016-11-03 22:53
I'm gonna have to close this as not-fixable because I have no idea why turning on that Accessibility setting interferes with the edibility of text fields. I'm not doing anything out of the ordinary and it's all Apple's built-in APIs. I guess...don't use that option?

**Closed by bdkjones** 2016-11-03 22:53 UTC
