### ISSUE TITLE
HTML files are not 'processed' by watcher. 

### ISSUE THREAD

**Issue by stenito** [bdkjones/CodeKit#631] opened 2020-10-25 20:37 UTC
**Quick, short summary:**
HTML files are not 'processed' by watcher. They are processed by 'building' the project.

**Expected results:**
Either process or copy the file.

**Actual results:**
The watcher does not 'process' HTML. It hangs on a changed HTML file and shows the status banner at the bottom: 'Processing file.html'. It hangs until restart of CodeKit.

Old files that were processed before or new files have the same bug.

**Comment by bdkjones** [comment] 2020-10-25 20:41
I’m not able to reproduce this on my end. Can you zip a demo project showing the issue and send it to me?

-Bryan

**Comment by stenito** [comment] 2020-10-25 20:52
Here you go. I created a new project with only a HTML file. Same bug. 

Steven



On 25 Oct 2020, at 21:41, Bryan Jones <notifications@github.com> wrote:


I’m not able to reproduce this on my end. Can you zip a demo project showing the issue and send it to me?

-Bryan

**Comment by bdkjones** [comment] 2020-10-25 22:59
Ah, okay. This does not happen initially. It occurs only when the Output Path has an existing file in place. I've released CodeKit 3.13.2 with a fix for this. Update to that version and you'll be all set. Thanks for the report!

**Closed as completed by bdkjones** 2020-10-25 22:59 UTC
