### ISSUE TITLE
Changes to imported files - no reload

### ISSUE THREAD

**Issue by ion-alexa** [bdkjones/CodeKit#638] opened 2021-01-17 05:00 UTC
I don't know if I misunderstood the concept, but it does not look like making changes to an imported .kit file does a refresh in the live preview. I have to make a change to the master file as well (the one importing it) to be able to see the change.
What is the point?

**Comment by bdkjones** [comment] 2021-01-17 05:04
Opening issues without a reproducible example demonstrating the problem leaves me with nothing to do. It’s not impossible that you have found a bug, but 99 out of 100 cases like this end up being user error—especially since you’re the only person reporting it. You also have not supplied the version of CodeKit you’re running, nor any information that would allow me to assist you.

**Comment by ion-alexa** [comment] 2021-01-17 05:29
My setup is very very very very very simple:
On the root I have:
- index.kit
- partials: _navbar.kit, _footer.kit

index.kit is a just a regular html5 page, with 2 imports:
< !-- @import "partials/_navbar.kit" -->
< !-- @import "partials/_footer.kit" -->

Making changes to either _navbar or _footer doesn't show up on the "live" website (using Chrome).

My Codekit is a fresh install (purcahsed it yesterday)

**Comment by bdkjones** [comment] 2021-01-17 05:42
The issue is the opening comment delimiter. You’ve added a space, which makes it invalid. Remove the space.

**Comment by ion-alexa** [comment] 2021-01-17 05:53
> The issue is the opening comment delimiter. You’ve added a space, which makes it invalid. Remove the space.
> […](#)
> On Jan 16, 2021, at 21:29, Ion Toporan ***@***.***> wrote: ﻿ My setup is very very very very very simple: On the root I have: index.kit partials: _navbar.kit, _footer.kit index.kit is a just a regular html5 page, with 2 imports: Making changes to either _navbar or _footer doesn't show up on the "live" website (using Chrome). My Codekit is a fresh install (purcahsed it yesterday) — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Oh, com on Bryan
The space is there just to make sure it shows here on Github, otherwise the editor will hide it/treat it as a comment.
There is no space on the actual code!

![2021-01-17_06-52-44](https://user-images.githubusercontent.com/69511200/104832335-b4fdd100-5890-11eb-91ea-7daa9fc68e8a.png)

**Comment by ion-alexa** [comment] 2021-01-17 06:07
Never mind! I deleted the config.codekit3 and rebuild the project. Looks like it's working again!
You may close this issue, if you want.
Thanks for your assistance!

**Comment by ion-alexa** [comment] 2021-01-17 07:41
> Never mind! I deleted the config.codekit3 and rebuild the project. Looks like it's working again!
> You may close this issue, if you want.
> Thanks for your assistance!

It worked fine, until I created a new kit (_breadcrumb.kit) file on the partials folder and imported to index.kit. Not updating anymore.
The only "fix" is to delete config.codekit3 and rebuild!!!

**Comment by bdkjones** [comment] 2021-01-17 09:50
You don't get the emails I get. I've had people scream at me and curse my app only to discover that they forgot the exclamation point. GitHub will display the text correctly when wrapped in backticks: `<!--`

As for the remaining issue: after adding the new partial file, does saving ANY imported partial file produce the issue or does the issue only manifest when saving the NEW partial file? If the latter, the project simply needs to be re-indexed. That should happen automatically, but can be prevented in some cases. To do it manually simply hit the refresh button in CodeKit's UI.

**Comment by ion-alexa** [comment] 2021-01-17 09:58
> You don't get the emails I get. I've had people scream at me and curse my app only to discover that they forgot the exclamation point. 
>

Sorry to hear that! It wasn't my intention to do that. But yeah, I get it. Blame the fool, not the tool! 👍 

>GitHub will display the text correctly when wrapped in backticks: <!--
>

Thanks for the tip!

> As for the remaining issue: after adding the new partial file, does saving ANY imported partial file produce the issue or does the issue only manifest when saving the NEW partial file? 
>
To be honest, I don't know! It just happens and I didn't pay attention if it's when I add the partial and save it or when I import it on the master and save the master!

**Comment by bdkjones** [comment] 2021-01-17 10:15
Just tested this over here. It appears that the *browser* is not being refreshed when the main Kit file is compiled, but the compiling process does indeed pick up the new imported file and correctly includes its contents. Refreshing the browser manually shows the new content. I'm not sure why this is the case, but I'll look into it.

**Comment by bdkjones** [comment] 2021-01-17 10:18
Oh, scratch all of that. The browser refreshing didn't work because my example file was not HTML; I just dumped a couple strings into the files.

The issue is resolved if you hit the Refresh button in CodeKit's UI after adding the new `@import` statement to the main file. That refresh correctly establishes the link between the main file and the imported one. That SHOULD be done without needing to refresh the project, so I'll look into what it's failing for Kit partials. In the meantime, refresh the project when you add a new @import and you'll be set.

**Comment by bdkjones** [comment] 2021-01-28 02:46
This is resolved in the next update, 3.14. Thanks!

**Closed as completed by bdkjones** 2021-01-28 02:46 UTC
