### ISSUE TITLE
Getting weird options for kit

### ISSUE THREAD

**Issue by wingsline** [bdkjones/CodeKit#222] opened 2016-10-28 15:34 UTC
**Quick, short summary:**

On a brand new project (attached one) I'm getting these options for the Kit language: 

**Expected results:**

![screen shot 2016-10-28 at 10 33 08](https://cloud.githubusercontent.com/assets/294228/19812128/f9b07fde-9cf9-11e6-9f6b-337190893cc6.png)

**Actual results:**

![screen shot 2016-10-28 at 10 27 33](https://cloud.githubusercontent.com/assets/294228/19811992/59bf5b3a-9cf9-11e6-8104-7eac4a513db3.png)

Clicking to another language and back, will give you the normal kit options.

**Exact steps to reproduce:**

New project, open project settings > Languages > Kit

**A link to download a simplified project or file that shows the issue:**

[SampleProject.zip](https://github.com/bdkjones/CodeKit/files/558766/SampleProject.zip)

**Your configuration (any details about your system that you think might be relevant)**

iMac Late 2013, 16GB ram

**Comment by bdkjones** [comment] 2016-10-28 18:00
Yea, this is a dupe of #219. It's definitely a bug and I'll have a patch out for it this weekend.

**Closed by bdkjones** 2016-10-28 18:00 UTC
