### ISSUE TITLE
Recursive processing of javascript files not working in CodeKit 3

### ISSUE THREAD

**Issue by Tklaversma** [bdkjones/CodeKit#272] opened 2016-11-15 16:30 UTC
**Summary:**
Recursive processing works in CodeKit 2, but not in CodeKit 3. What I mean by `recursive processing` is the following:

1. CodeKit merges a number of files with no syntax check and no minify to a new file called `merged.js`. This all happen because of the file `needs-processing.js` that look like this:
```
//@codekit-append "_init.js"
//@codekit-append "_first.js"
//@codekit-append "_last.js"
```
2. I have a file called `final.js` that processes `merged.js` on change. So when I make a change in `_init.js`, it will make the non-minified file `merged.js` and `final.js` is reproduced because `merged.js` has changed. But for some reason, CodeKit 3 does not see the change in `merged.js`....so `final.js` is not reproduced.

**Problem:**
When I make a change in `_init.js`, `merged.js` is reproduced, but `final.js` does not reproduce in CodeKit 3. But all works fine in CodeKit 2.

**My configuration (any details about your system that you think might be relevant)**
macOS Sierra 10.12.1
CodeKit 3

**Comment by Tklaversma** [comment] 2016-11-22 13:29
No one?

**Comment by me-benni** [comment] 2016-11-22 16:02
I can't quite follow with your setup.
You concatenate your `_x.js` files in a file, that outputs without changes into another file, that gets processed?
Why not process them in the first step? e.g. skip the 'output without changes' step

I tried to reproduce your setup, but I can't further process the `merged.js` since CK knows it's a 'Output File'

**Comment by Tklaversma** [comment] 2016-11-22 16:07
@me-benni 
I have a bunch of files that I want to combine without checks. After they are combined, I want them to minify with checks.

Main reason for this wrongfull way is that I want all files inside jQuery, like so:
```
jQuery(document).ready(function(){
    // HERE I WANT ALL FILES COMBINED TO RESIDE
});
```

and the following does not work:
```
jQuery(document).ready(function(){
    //@codekit-append "init.js"
    //@codekit-append "next.js"
    //@codekit-append "last.js"
});
```

If you have a way for this to work, let me know :)

**Comment by me-benni** [comment] 2016-11-22 16:19
You don't necessarily need all your JS files in the document.ready() function.
Just put your entry-point into the ready-function.

```js
function init() {
  // init stuff
  // load stuff
  // set stuff
}
```

this and everything else you put into one file that gets processed and lastly you call

```js
jQuery(document).ready(function() {
  init()
})
```

I guess that should do the trick?

**Comment by Tklaversma** [comment] 2016-11-22 16:23
@me-benni 
Huh? But that still leaves me with the same problem, right? I have multiple files with multiple events and functions, that all have to reside in de jQuery(document).ready.

Maybe I'm missing something (if so sorry).
Could you please work out an example with `//@codekit-append` of multiple files?

Furthermore, thanks for the help so far!

**Comment by bdkjones** [comment] 2016-12-02 01:06
This should be issue #279 and should be fixed in my next update. I'll likely get that pushed out tomorrow.

**Closed by bdkjones** 2016-12-02 01:06 UTC

**Comment by AlejandroColinaPew** [comment] 2017-06-16 00:18
It would be wonderful if CK would just help me build javascript,less,css,etc.files in any way I like, and then let me feed that it into babel, less,etc unhindered. 

CK used to be closer to that, but it no longer allows one to use output files in a workflow. Say, concatenate all of this stuff, now process it, transpile, maybe concatenate some more.

Id love to do this:

```
$.noConflict();
(function( $ ) {
  $(function() {
//@codekit-import  "/JS_section1.js"
//@codekit-import  "/JS_section2.js"
//@codekit-import  "/JS_section3.js"
 });
})(jQuery);
```

Truly, a GUI tool like that is sorely needed.

**Comment by bdkjones** [comment] 2017-06-16 02:29
Using output files in a workflow is fully supported, both with Hooks and general import/prepend/append statements. 

What you're trying to do there is really bad practice. Functions should never be split across files. It leads to bugs, scope collisions, etc. You'd be better off factoring the structure of your code so that things in those three Javascript files are self-contained functions that can be called on document ready (via jQuery) or with the dom  ready event listener via Javascript.

**Comment by AlejandroColinaPew** [comment] 2017-06-16 14:32
There is @codekit-import?

**Comment by bdkjones** [comment] 2017-06-16 16:03
No; import is recognized in languages that have that syntax. CSS, Sass, kit, pug, etc.
