### ISSUE TITLE
Refresh issue in Firefox 57

### ISSUE THREAD

**Issue by tbnv** [bdkjones/CodeKit#416] opened 2017-11-29 16:03 UTC
**Quick, short summary:**
I'm using Firefox 57. When I save SASS files, they are processed but there is an issue with refreshing the page in the browser. The problem doesn't occur in other browsers.

**Actual results:**
The page is not refreshed and this error shows up in the console:
```
Error: Permission denied to access property "mediaText"    localhost:5757:30:2917
```

If I save the file a second time, the error message is completed with this:
```
Error: Permission denied to access property "mediaText"    localhost:5757:30:2917
A refresh was requested, but the page is already refreshing. The new refresh request was ignored.    localhost:5757:30:4756
```

The line 30 in the web inspector is the JS injected by CodeKit.

**A link to download a simplified project or file that shows the issue:**
<img width="892" alt="capture d ecran 2017-11-29 a 17 01 51" src="https://user-images.githubusercontent.com/1021579/33384792-470c6f5c-d527-11e7-972b-36ca55faf95e.png">

**Your configuration (any details about your system that you think might be relevant)**
macOS 10.13.1
iMac 5K
CodeKit 3.4.2 - build 26148
Firefox 57.0
Atom 1.22.1

**Comment by bdkjones** [comment] 2017-11-29 16:58
Is FF57 the new Quantum one? Are you running any browser plugins or security software?

**Comment by tbnv** [comment] 2017-11-29 17:05
Yep, it's Quantum.

I tried with all plugins disabled (1P, uBlock, HTTPS Everywhere) but the problem remains, and I don't use specific security software.

**Comment by bdkjones** [comment] 2017-11-29 21:10
Okay. Does the issue happen on every page and project you try, or just this one? Can you reduce it to a very simple project that can be posted here to test with?

**Comment by tbnv** [comment] 2017-11-30 10:15
I have troubles to replicate the issue. It doesn't happen all the time. Sometimes, after a full page refresh, I cas save the SCSS files a few times before it happens, then it comes back. And it's absent from a new test project I created to post here.

**Comment by AlexandreBonneau** [comment] 2017-12-05 18:53
For info, I'm also encountering the `Error: Permission denied to access property "mediaText"` error message in a personal project, and it happens only in Firefox 56.0b12, not in Firefox 52.5 nor Chrome 62.

It happens when I try this:
```js
const media = document.styleSheets[i].media;
if (mediaType === 'object') {
     if (media.hasOwnProperty('mediaText') &&
        (media.mediaText === '' || (media.mediaText.indexOf('screen') !== -1))) {
        styleSheet = document.styleSheets[i];
    }
}
```

while `mediaText` always exists and can be seen in the console, merely trying to access it from the script results in that error above. 😠

**Comment by tbnv** [comment] 2017-12-05 22:48
@AlexandreBonneau Sorry but you're sure you use FF 56.0b12 and not FF 57.0b12? Because FF 57 has just been released a few days ago.

**Comment by AlexandreBonneau** [comment] 2017-12-06 00:50
Yes I'm sure. I pinned the version to prevent this browser to switch to v57+ ; the quantum version nuked ~40 extensions I'm using everyday and am not prepared to drop those!

**Comment by AlexandreBonneau** [comment] 2017-12-06 01:26
Also, do note that that bug does not appears in Firefox 58.0b8 nor 58.0b9 !

**Comment by bdkjones** [comment] 2017-12-06 03:09
This sounds like a bug in FireFox that got fixed in a later release.

**Comment by AlexandreBonneau** [comment] 2017-12-06 07:26
@bdkjones sorry I edited my message before your answer as I found out that the problem is still present in the latest Firefox version.

It seemed to work, but after a few refresh the same error message was shown again 😢

**Comment by tbnv** [comment] 2017-12-06 08:13
In a comment above I said the issue doesn't happen in a new test project I wanted to post here. But I tried again and it actually does.

So if you want a test project, here is one. 😉

You'll see that after a few refreshes upon SASS processing ***** , refresh will hang and the error will appear in the console. Maybe it will be after 2 saves, maybe after 10 or 20. I really can't predict this.

( ***** On my side I didn't see it occur when saving HTML or PHP, due to full page refresh I guess.)

[test.zip](https://github.com/bdkjones/CodeKit/files/1534349/test.zip)

**Comment by bdkjones** [comment] 2017-12-06 16:22
Ok. I’m traveling for the next week or so, so it’ll take me a bit to investigate. I’ll look into it though!

**Comment by tbnv** [comment] 2018-01-08 01:29
@bdkjones FYI, problem still present after recent Firefox upgrades.

**Comment by RubiousShaun** [comment] 2018-01-15 09:35
I am also experiencing this issue.

**Comment by mostafanasergivechi** [comment] 2018-01-25 02:00
The same here, I don't get it.

**Comment by shaynestatzell** [comment] 2018-01-31 17:09
+1

**Comment by joopvos** [comment] 2018-02-05 15:40
+1 with FF 59.0b6 (64-bit) ... :(

**Comment by alex-miura** [comment] 2018-05-21 14:54
Not working on: 61.0b6 (64-bit) - might try the nightly channel - currently on Aurora channel.

**Comment by mejobloggs** [comment] 2018-05-31 02:02
Not working 61.0b9 either

**Comment by tbnv** [comment] 2018-05-31 05:08
Yeah… I'm also experiencing the issue with FF 60 stable channel.

@bdkjones I opened the ticket back in November, about 6 months ago. Your latest answer was posted in December. Sorry to say this, but now I find it quite a bit long. Could you please at least give us some news, if it will be fixed _soon_, etc.?

**Comment by bdkjones** [comment] 2018-05-31 07:45
I hear ya. The trouble is: I don't know why FireFox is behaving this way. Given that no other browsers show the issue, that the issue came about in a recent FF update, and given the fact that FF has always been a giant pain to deal with, I've got a sneaking suspicion that this is a FF bug.

I have not given up on finding a workaround, however.

**Comment by bdkjones** [comment] 2018-11-07 21:50
Yea, the trouble is that I think this problem is in Firefox. I have no idea what causes it, no other browser has any similar problem, and Firefox has a reputation for being finicky and stupid.

**Comment by heartfield** [comment] 2018-11-08 10:44
Is this an issue that could be filed on Bugzilla? I would do it myself if I could but I don't know how to properly describe the problem.

**Comment by ArianeNubee** [comment] 2019-06-13 20:13
I think I found a workaround. In about:config, find the following values :
browser.tabs.remote.useCrossOriginOpenerPolicy
browser.tabs.remote.useCrossOriginPolicy

Toggle them to **true**. I did this an hour ago and so far, browser refreshing hasn't stopped working like it used to.

I've been working like this for about an hour, and CodeKit's auto-refresh still hasn't died as it used to all the time. So I think it's safe to say it works. I'll come back and say something if it dies again. In the absence of other news, assume it's kept working.

Note that I'm pretty sure this has security implications I haven't researched. Honestly, I don't really know what I'm doing here. But hopefully knowing that this workaround works can guide @bdkjones towards a real fix.

**Comment by bdkjones** [comment] 2019-06-13 23:36
Interesting. Is there any documentation on exactly what those policies **do**?

**Comment by ArianeNubee** [comment] 2019-06-14 13:07
https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features
I found this. Cmd+F your way to "browser.tabs.remote.useCrossOriginPolicy".

Hope it helps.

**Comment by ArianeNubee** [comment] 2019-06-14 13:35
Update: Auto-refresh died once after working for hours and even through the night (the computer was on Sleep). I restarted CodeKit's browser refresh server and my browser and it's been working fine for a while. Looks like it improves the issue but doesn't prevent it entirely.

**Comment by bdkjones** [comment] 2019-06-14 19:10
Its normal for the refresh server to disconnect when the computer sleeps for a long period, as the network interface usually disconnects. CodeKit restarts its servers when that happens to capture the new IP address of the machine.

**Comment by ArianeNubee** [comment] 2019-06-28 19:08
Suggestion: If you don't manage to solve this for now, it would be awesome if you could catch the error, when it occurs, and force a full browser refresh instead. It would make the UX much better when it happens. Very frustrating to wonder and search frantically for the reason your styles aren't applying, only to discover it was a refresh problem.

It should be possible, since I've never noticed full refreshes (such as when saving PHP and JS files) die like CSS live refreshes do.

**Comment by bdkjones** [comment] 2019-06-28 20:01
That's actually a pretty genius idea. I'll look into it.

**Comment by bdkjones** [comment] 2019-07-10 04:03
I wish I could say that I have fixed this issue because I am an incredible, ingenious developer. 

In fact, I have fixed this issue because I am a lazy developer and I set CodeKit to use an un-minified version of the refresh script while I was debugging. I noticed that, suddenly, Firefox worked just fine. For some reason, minification of the refresh script is what caused this problem—likely because Firefox's JavaScript engine is dumb.

I use CodeKit itself to minify/mangle the refresh script. By tweaking some of the minification options, I was able to work around Firefox's idiosyncrasies and the version of CodeKit that should ship tomorrow afternoon resolves this issue.

**Comment by ArianeNubee** [comment] 2019-07-10 09:40
That's weird, and pretty awesome. Did you figure out exactly what was breaking it? In case I also run in some problems with my JS.

**Comment by bdkjones** [comment] 2019-07-10 13:43
Yes. I disabled the “conditionals” option in Project Settings > Terser.

**Comment by ArianeNubee** [comment] 2019-07-31 13:50
The problem still appears to exist in 3.9.2. Did you implement your fix in the last update? I didn't see it in the changelog.

**Comment by bdkjones** [comment] 2019-08-01 06:05
Yes; the change went live in 3.9.2 according to my git history. Can you send me the project you're having trouble with so I can test it over here? The project I tested with worked correctly in Firefox in 3.9.2

**Comment by ArianeNubee** [comment] 2019-08-01 12:53
https://drive.google.com/file/d/1Xc1j5UVZGYOMuNZsSXYUTvazVisJoKPY/view?usp=sharing
Here you go.

Also, if it's relevant information, I'm using Firefox 68.0.1

**Comment by bdkjones** [comment] 2019-08-05 04:27
Okay, so that project is too big. Google Drive is actually hanging and won't let me download it. I do see that it's a massive WordPress project. There's just too many variables involved there.

Can you reproduce the issue with a simpler site? Try a single `index.html` page and a single `style.scss` file that compiles to a CSS file you include on the page. Does the issue reproduce in that case? If so, please send me that test project.

Also: which version of macOS are you running? Do you have any plugins running in FireFox? I'm trying to narrow down differences between your environment and mine.

**Comment by ArianeNubee** [comment] 2019-08-05 05:38
That's really weird. It's literally one tar.gz archive, and it only weighs 11 MB (I stripped all the heavy stuff and all the php, as well as WordPress itself). It shouldn't be complex for Drive to give you a download. Maybe I see l should've stripped the JS, since a node_modules folder can get pretty complex.

Anyway, I'll try to reproduce the issue in a simple project and will get back to you soon. I'll also give you the details you asked for then.

**Comment by ArianeNubee** [comment] 2019-08-14 18:18
Sorry for the delay. I wasn't getting the error anymore and I was puzzled. I figured out why: it stopped happening randomly, but whenever I leave the computer and it falls asleep, when I come back, this happens :

- The mediaText error happens whenever I save CSS
- An error "A refresh was requested, but the page is already refreshing. The new refresh request was ignored." happens whenever I save HTML/anything that requires a full refresh.

I realize that the computer sleeping shuts down network connections and messes up a lot of things, but can something be done to force a full refresh and re-establish the connection once the computer is woken?

**Comment by bdkjones** [comment] 2019-08-14 18:38
Ah, good.

Unfortunately, no. Once the websocket connection is closed (the computer goes to sleep and disconnects the network interface) CodeKit no longer has a way to communicate with the page to tell it to reload.

You should see a red banner at the top of the page in those instances and clicking that banner will force-reload the page and re-establish the websocket connection with CodeKit.

**Closed by bdkjones** 2019-08-14 18:38 UTC

**Comment by ArianeNubee** [comment] 2019-08-14 18:42
The banner doesn't appear. Also, I refreshed the page several times, but the error is still happening. I also restarted CodeKit's browser refresh server, to no avail. A hard refresh (Cmd + shift + R) seems to have fixed it for now, though.

I don't think my previous explanation holds.

**Comment by bdkjones** [comment] 2019-08-14 18:43
Are you running any browser plugins in Firefox?

**Comment by ArianeNubee** [comment] 2019-08-14 18:48
Here is a list :

- Plugins :
    - Cisco H264 video plugin
    - Google Widevine content decryption module
- Extensions : 
    - 1Password extension (desktop app required)
    - Clear Cache
    - Firefox DevTools ADV Extension
    - LastPass : Free password manager

**Comment by ArianeNubee** [comment] 2019-08-14 19:40
More information: my computer went to sleep and the bug did not happen after waking it up. No banner or anything; it's like it never went to sleep at all. I'm not sure sleep mode has anything to do with the bug.

**Comment by bdkjones** [comment] 2019-08-14 19:56
Try disabling all of those and see if the issue persists.

**Comment by ArianeNubee** [comment] 2019-08-14 20:08
I tried in [safe mode](https://support.mozilla.org/en-US/kb/troubleshoot-firefox-issues-using-safe-mode). The issue still happens.

**Comment by iclang** [comment] 2019-08-21 16:20
I can confirm this happened today using CodeKit 3.9.2 - Build 31491 and Firefox Quantum 68.0.2 in Safe Mode.

Here is site I am working on if that helps. Let me know what else you might need.

https://www.dropbox.com/s/6x4dj4bi7fjodu1/CodeKitRefreshIssue.zip?dl=0

**Comment by Ariane-B** [comment] 2020-01-30 19:50
I came back to work after several months off to notice the issue is closed, yet the bug still happens very often. Any news?

**Comment by bdkjones** [comment] 2020-02-03 05:22
I haven't been able to reproduce this after my last fix, but I can force FireFox to use full-page reloads. Unfortunately, FireFox is a pretty lousy browser in terms of JavaScript parsing and execution.

**Comment by Mattrushka** [comment] 2020-02-03 08:27
I really appreciate your product & work but I disagree with the FireFox bashing here. I have never experienced mutli-browser syn/refresh issues in my projects when using different tools like Grunt, Gulp or Node.js. I personally have no problem developing & testing in Chrome but maybe other people would appreciate to know that Codekit does not support all major browsers in terms of browser sync before buying the product.

**Comment by bdkjones** [comment] 2020-02-03 16:01
Well, this issue manifests only in Firefox and it’s related to their Javascript execution engine. Literally every other browser is fine—not just Chrome. Edge, Internet Explorer, Brave, Android, etc. Firefox is frequently a pain point. For example, Firefox is the only browser that does not integrate with the macOS keychain for storing and reading certificates. I’ll take another look and see if I can reproduce the issue here.

**Comment by heartfield** [comment] 2020-02-04 11:39
I can confirm the refresh bug still happens frequently. I use Firefox as my main browser for developing. Because of this bug it's hard to know if a CSS change I made is not working properly or if the Codekit refresh script has bugged out again. Any fix or workaround would be welcome so I can stop refreshing manually.

**Comment by Ariane-B** [comment] 2020-02-04 12:42
Honestly, whether or not you can reproduce and fix the issue at this point, I'd really appreciate it if you could find a way to alleviate this huge pain. I hate Chrome's interface for development, and having to use it just because auto-refresh won't work in Firefox is terribly frustrating.

Unless you're confident you can fix it for real, could you please, at least temporarily, force a full-browser refresh whenever the bug happens? That would at least fix the numerous moments where we're wondering if we're targetting the wrong selector or if CodeKit refreshing died on us again.

As for investigating the issue, would reaching out to someone at Mozilla be a potential solution? Maybe they'd have helpful insight? It's their own engine, after all.

**Comment by bdkjones** [comment] 2020-02-04 19:18
I’d love to, but I need a reproducible test case to investigate. Can you post a very small demo project that shows the issue? And also include details about your version of FF and any plugins/extensions running in it. I need to reproduce the issue before I can do anything.

**Comment by bdkjones** [comment] 2020-02-04 19:22
I’ve already reached out to Mozilla—there’s an open bug about this JS issue that dates back years. It’s just not a priority for them. If I recall correctly, it’s a timing issue with security scoping on the “mediatext” property of a stylesheet. 

I definitely understand the frustration. If you can post a demo project that reproduces on your end, I’ll take a look at this and either find a workaround for Mozilla’s bug or force full-page reloads on Firefox. The next CodeKit update should release in a couple weeks and I can have it in that.

**Comment by bdkjones** [comment] 2020-02-05 02:32
As far as I can tell, this issue only manifests when a CSS stylesheet is complex enough to trigger the timing bug or when there are enough stylesheets on the page to do the same.

I just re-tried the demo projects I use to test CodeKit over here and they all worked flawlessly in Firefox 72.0.2. I'm not able to reproduce the issue.

If you have a project that DEFINITELY shows the issue, please send me a download link. Ideally, it should be a project that does not depend on any external resources such as a WordPress database, etc.

**Comment by iclang** [comment] 2020-02-05 19:20
Hey @bdkjones, I uploaded an example awhile back. Hope that helps.

https://github.com/bdkjones/CodeKit/issues/416#issuecomment-523533960

**Comment by bdkjones** [comment] 2020-02-06 00:50
Yep. That example is the one I’m using, but I’ll grab a fresh copy just in case.

Out of mere speculation: what hardware are the folks still seeing this issue using? I’m wondering if I can’t reproduce it because I’m on faster hardware.

**Comment by Ariane-B** [comment] 2020-02-06 03:37
I'm sorry, I was totally swamped at work today and couldn't even think about this issue. I'll try to prepare an empty project for you on Monday. I'll tell you all the details about my machine then as well.

**Comment by iclang** [comment] 2020-02-06 04:05
@bdkjones I am using a MacBookPro 2018 (2.9GHz i9; 32GB)

**Comment by bdkjones** [comment] 2020-02-06 19:21
So much for that theory. I’m on the exact same machine.

**Comment by Ariane-B** [comment] 2020-02-13 22:10
I'm really sorry for the delay. I've been busy and kept forgetting.

My laptop's details are:

> macOS Catalina (10.15.2)
> MacBook Pro (Retina, 15-inch, Mid 2015)
> 2.5 GHz Intel Core quad-core
> 16 GB 1600 MHz DDR3 memory
> Graphics: AMD Radeon R9 M370X 2 GB / Intel Iris Pro 1536 MB

Now, as for the bug. I tried for several long minutes to reproduce the bug in a simple test project. Without success. Then I switched CodeKit to my normal work project, refreshed my browser, and saved my SCSS. The bug happened instantly.

I switched back to the simple project and refreshed my browser. Bingo, the bug was still there. It looks like something in my big, complex project caused the bug and it stayed? Looks like we have a hint here.

I'm including the simple project.

The big project is a pretty heavy WordPress website. Would you like me to send it to you? It's probably not a good idea to share all of my job's code publicly.

[codekit-test.zip](https://github.com/bdkjones/CodeKit/files/4201491/codekit-test.zip)

**Comment by bdkjones** [comment] 2020-03-02 06:18
Well, I can't run the WordPress site over here to test with, but perhaps you can transform it into a page that's still complex enough to reliably show the issue? 

In other words, grab the HTML from the browser and throw that into an index.html file that uses the same stylesheet. If we can get a static page that reliably triggers the race condition, I can use that to come up with a workaround.

**Comment by bdkjones** [comment] 2020-03-03 01:50
Alright, after much investigation, here's the deal: 

# It's Mozilla's Issue

Mozilla has (apparently) finally admitted that this is a bug on their end. Someone had the same issue using refreshes from Microsoft VisualStudio: https://developercommunity.visualstudio.com/content/problem/738525/vs-2019-css-auto-sync-not-working-pt2.html

The support tech from Microsoft updated a Mozilla bug with a reproducing test case: https://bugzilla.mozilla.org/show_bug.cgi?id=1423300#c8

The Mozilla guy was able to see the problem, but it was intermittent for him as well. As was the case here, nothing the Microsoft people tried solved the issue because...it's a bug in Firefox. 

Nobody, anywhere, was able to reproduce this problem in any other browser. 


# The Inspector Must Be Open

The issue reproduces **ONLY** when the inspector is open in Firefox. Without the inspector open, refreshes work all day long. 

Once the issue occurs, you must close the inspector and then reload the page manually once. At that point, the issue will not re-occur until the inspector is reopened. 


# Reasons MediaText Is Needed

CodeKit's refresh script accesses the `mediaText` property of a `<link>` element so that it can set the correct media type once it reloads that element. It is **POSSIBLE** for me to modify the script such that, if you're using Firefox, CodeKit won't access `mediaText` and therefore won't know what to set on the reloaded `<link>` element.

In practice, this will mean that if you have a stylesheet for `print`, the styles from that stylesheet will be applied to the website on-screen after a refresh because the `mediaType` property isn't set correctly because Firefox has a bug. 

That would be very freaking annoying, obviously.

# Other Options

1. CodeKit could stop offering injection stylesheet reloads in Firefox and simply reload the entire page. That's obviously less than ideal. It should be possible for me to do this only when the bug manifests. But that will be any time you save a file with the Firefox inspector open.

2. When the issue occurs, CodeKit could show you an alert informing you of the Firefox bug and telling you to close the inspector and reload the page once in order to re-enable live-refreshing.

3. You guys could pressure Mozilla to get their act together and fix the issue. It's been years, after all.

4. We could all switch to Safari?

**Comment by bdkjones** [comment] 2020-03-03 01:54
The reason I couldn't reliably reproduce this issue, in retrospect, was that it never happens without the inspector open. It was only when I opened the inspector to verify that no errors were being logged to the console that I saw the issue start to occur. This is also why I mistakenly thought an earlier change had fixed it—I tested the change with the inspector closed and the bug does not manifest in that state.

**Comment by bdkjones** [comment] 2020-03-03 03:18
# Update

I may have stumbled on a pretty elegant workaround. Turns out this doesn't **always** happen when the inspector is open. It seems to be only when the inspector is first opened, and only when it's on the actual "inspector" tab that shows the DOM. That will produce the bug on the first injection-reload. 

However, I modified my script to detect that and force a full-page reload. After that completes, injection-reloads seem to work again, regardless of the inspector being open. 

I'll need to test this some more and see if I can find a pattern, but it looks like the workaround might just be random full-page reloads when working in Firefox with the inspector open.

**Comment by Ariane-B** [comment] 2020-03-03 15:23
Amazing! After all that time, the bug is (kinda) understood at last! Looks like you don't need my site anymore after all.

I mean, even more amazing would be if the bug in Firefox were fixed altogether, but I like your solution. Only one full refresh when it happens and it fixes the bug from then on? That's a very satisfying solution.

Thanks. You're a genius.

PS: Safari has several weird CSS/JS bugs too.
