### ISSUE TITLE
Indicator in menu bar if file watcher is paused

### ISSUE THREAD

**Issue by supermueller** [bdkjones/CodeKit#292] opened 2016-12-21 14:38 UTC
It would be helpful, if the Codekit icon in the menubar will reflect the status of the file watcher. Sometimes I am wondering why my files aren’t processed anymore and the figure out that I just have forgot to un-pause the file watcher.

**Comment by davegillem** [comment] 2016-12-21 17:58
Duplicate of issue #245

**Closed** 2017-01-31 00:56 UTC
