### ISSUE TITLE
Version 3.0.8 build 25704 doesn't respond on startup

### ISSUE THREAD

**Issue by didjee** [bdkjones/CodeKit#333] opened 2017-03-15 10:31 UTC
**Quick, short summary:**
Version 3.0.8 build 25704 doesn't respond on startup. A force quit and restart doesn't solve this.

**Exact steps to reproduce:**
Update version 3.0.6 build 25568 to version 3.0.8 build 25704

**Your configuration (any details about your system that you think might be relevant)**
MacPro 2,66 GHz Quad-Core Intel Xeon - 16 GB ram
macOS 10.11.6 (15G1217)

**Comment by bdkjones** [comment] 2017-03-15 17:11
Duplicate of #332

**Closed by bdkjones** 2017-03-15 17:11 UTC
