### ISSUE TITLE
CraftCMS Twig template files _name.html are set to "ignore it" by default

### ISSUE THREAD

**Issue by TC72** [bdkjones/CodeKit#331] opened 2017-03-10 08:52 UTC
The naming convention when using Twig inside CraftCMS is to name partial templates with an underscore, similar to SASS. For example product/_entry.html.

By default when CodeKit finds this type of file it is set to "Ignore it". I tried getting around this in the settings by configuring .html as another language with the action set to "Copy" but it doesn't work. I guess this is because CodeKit already handles .html files internally.

This issue caused me to lose a days work, not because of CodeKit but thanks to CraftCMS reporting a missing template as a standard 404 "Page not found" error with zero details about there being a template missing even when you kick it into debug mode. It actively redirects you to the standard 404 so any debug code you add to trace a routing problem gets lost on the redirect.

**Comment by bdkjones** [comment] 2017-03-10 14:55
I'm a little confused. Files with leading underscores are generally never compiled on their own; they're imported into other files. I haven't used Twig so I'm not familiar with their setup.

**Comment by TC72** [comment] 2017-03-10 14:58
They don’t need to be compiled but they do need to be copied over to the build folder.

**Comment by TC72** [comment] 2017-03-30 10:54
To give you an example of a plugin I installed this morning:
https://github.com/elliotlewis/Redactor-Extras

There is a file called:
redactor
extras/template/_settings.html

This is a standard format adhered to by plugins created for Craftcms. Every time I install a plugin in this way I then have to go through and manually tell CodeKit not to ignore the _name.html template files.

![codekit](https://cloud.githubusercontent.com/assets/402357/24500988/98652a90-153f-11e7-9b9b-8f026e4c652e.png)

**Comment by bdkjones** [comment] 2017-03-30 20:02
Yea, I see the issue, it's just that the CraftCMS people are sort of abusing this standard. Those HTML files aren't **REALLY** partials. A partial is a file that's imported (combined) into another file. The partial itself is never used directly. In CraftCMS, however, that `_settings.html` *is* used directly (hence its need to be copied into the build folder).

I'm stuck between a rock and a hard place because if I change CodeKit to stop auto-ignoring files with leading underscores, **TONS** of people will be incredibly frustrated because now all their Sass, Less and Stylus partials are attempting to compile and throwing errors because those files were never meant to compile on their own, so now all of THOSE users have to go select their paritals and set their Output Action to ignore.

The *correct* solution is for CraftCMS to stop abusing the leading underscore.

**Comment by bdkjones** [comment] 2017-03-30 20:04
In short, the app's current approach is perfect for 99% of users. You're the 1% who's using a CMS that doesn't conform to standards, I'm afraid. I know that's super irritating, but have you tried convincing the CraftCMS folks to follow the standard? Perhaps opening an issue and referencing this thread would help.

**Comment by TC72** [comment] 2017-03-30 20:18
I agree with what you’re saying and now I know this happens I can catch it each time. The problem was the first time this happened when it took me a day to figure out why it wasn’t working. It was made 100x worse by CraftCMS spitting out a generic 404 error instead of telling me it couldn’t find a template.

I’m not disagreeing with you but there is a definite reason for a template having an underscore at the start. If you create a news section for example which has an index at news/index.html and individual news items found by a slug which could be the date, news/2017-03-30.

The template file for the main index page would be in a file called news/index.html but the template for the individual news stories would be news/_entry.html. The underscore ensures the craft router will not allow someone to access the template just by going to the url news/_entry.html.

**Comment by bdkjones** [comment] 2017-04-01 18:50
Yea, I hear you. Generally, templating engines keep their templates in an entirely different folder, which lets them limit access with a `.htaccess` file blocking that folder entirely, etc. 

I don't know what I can do about CraftCMS; for now you'll just have to toggle those HTML files to copy on build.

**Comment by shanerobinson** [comment] 2017-08-03 22:28
I can also confirm that this is a problem for not only CraftCMS developers (of which I am one) but it's a problem for any file with a leading underscore.... I use PUG when developing in Jekyll and use files with underscores for includes and partials in order to keep dev and maintenance more organized and structured. 

I don't have a problem with CodeKit (which is AMAZING btw!!!) not copying or compiling by default files with leading underscores...I’m happy to change those few as needed. The problem is that CodeKit WILL NOT KEEP THE SETTING FOR A FILE when I change it. Everyday when I launch CodeKit and fire up a CraftCMS project, the files with leading underscores that I've previously set to "compile" or "copy" have reverted back to Ignore. 

I reset them to "compile" or "copy" and the next day they are ignored again. And not all of them. Just some of them and then the next day some other files will be ignored. It seems to be completely random which files ARE and which are NOT ignored from day to day. And if I switch CodeKit to a different project, and then back to my CraftCMS project, a seemingly new random set of _files will be ignored...which had previously been set to "compile" or "copy" earlier that day. 

Would LOVE to see this fixed...And then CodeKit will be perfect!

**Comment by bdkjones** [comment] 2017-08-03 22:47
I'd need to see an example project that shows this issue, along with an exact set of steps to reproduce it.

When you manually change the output path or output action of a file, CodeKit sets a flag on that file's settings that says, "The user set this manually; don't change it automatically any more." 

If you're using something like Git and you're pushing/pulling changes, you're likely applying different settings files that may or may not have that flag set for the files in question. That would explain this behavior.

**Comment by shanerobinson** [comment] 2017-08-04 20:14
I'm using Atom for my editor and Tower to manage GIT. How can I provide you with the "example project"?

**Comment by bdkjones** [comment] 2017-08-04 20:32
Are you pausing CodeKit's file-watching before performing Git actions? See codekitapp.com/help/git/

**Comment by shanerobinson** [comment] 2017-08-05 20:07
D'oh!!!  Deep Thanks, @bdkjones!  That would be the problem... Very Sorry to waste your time on something that was clearly in the docs and that I had seen but forgotten.

**Closed** 2017-08-17 04:35 UTC
